//#region imports
import type * as ora from 'ora';
import { TaonTempDatabasesFolder, TaonTempRoutesFolder } from 'taon/src';
import {
  config,
  dockerTemplates,
  dotTaonFolder,
  fileName,
  folderName,
  taonContainers,
} from 'tnp-core/src';
import { CoreModels, fse } from 'tnp-core/src';
import { _, UtilsOs } from 'tnp-core/src';
import { crossPlatformPath, path, Utils } from 'tnp-core/src';

import { CURRENT_PACKAGE_VERSION } from './build-info._auto-generated_';
import type { EnvOptions } from './options';
import { DeploymentReleaseData } from './project/abstract/taon-worker/deployments/deployments.models';

// import type { Project } from './project/abstract/project';
//#endregion

export const whatToLinkFromCore: 'src' | 'src/lib' = 'src/lib';
// export const whatToLinkFromCore: 'src' | 'src/lib' = 'src/lib';

/**
 *  '' - when whatToLinkFromCore is src
 *  'lib' - when whatToLinkFromCore is src/lib
 *  'deep/folder' - when whatToLinkFromCore is src/deep/folder
 */
export const whatToLinkFromCoreDeepPart =
  whatToLinkFromCore === ('src' as any)
    ? ''
    : (whatToLinkFromCore as string).replace('src/', '');

export const keysMap = {
  destinationDomain: 'dn',
  projectName: 'pn',
  releaseType: 'rt',
  version: 'ver',
  envName: 'enm',
  envNumber: 'enu',
  targetArtifact: 'ta',
} as Required<{ [key in keyof DeploymentReleaseData]: string }>;

export const dirnameFromSourceToProject = (linkToSource: string): string => {
  const orgParamLinkAbs = linkToSource;
  linkToSource = fse.realpathSync(linkToSource);
  linkToSource = crossPlatformPath(linkToSource);
  const orgRealLinkToSource = linkToSource;
  const howManyDirname = whatToLinkFromCore.split('/').length;
  _.times(howManyDirname, n => {
    // console.log(`dirname action ${n}/${howManyDirname}`);
    linkToSource = crossPlatformPath(path.dirname(linkToSource));
  });
  linkToSource = crossPlatformPath(linkToSource);
  // console.log({ linkToSource, orgRealLinkToSource, howManyDirname });

  if (path.basename(linkToSource) === 'src') {
    // console.log(`FIXING NOT PROPER LINK TO SOURCE ${orgParamLinkAbs}`);
    linkToSource = crossPlatformPath(path.dirname(linkToSource));
    // if (whatToLinkFromCore === 'src') {
    //   try {
    //     fse.unlinkSync(orgParamLinkAbs);
    //   } catch (error) {}
    //   Helpers.createSymLink(
    //     crossPlatformPath([linkToSource, whatToLinkFromCore]),
    //     orgParamLinkAbs,
    //   );
    // }

    // linkToSource = crossPlatformPath(path.dirname(linkToSource));
  }

  return linkToSource;
};

export const DUMMY_LIB = '@lib';

export const DOCKER_COMPOSE_FILE_NAME = 'docker-compose.yml';
export const DOCKER_FOLDER = 'docker';
export const BASE_TEMP_DOCKER_FOLDER = 'tmp-docker';

export const DOCKER_TEMPLATES = 'docker-templates';

export const ACTIVE_CONTEXT = 'ACTIVE_CONTEXT';

export const friendlyNameForReleaseAutoConfigIsRequired = false;

export const iconVscode128Basename = 'icon-vscode.png';

export const taonIgnore = '@taon' + '-' + 'ignore';

export const DEBUG_WORD = 'Debug/Start';

export const scriptsCommands = [
  'taon init',
  'taon start',
  'taon build:lib',
  'taon build:watch:lib',
  'taon build:watch:app',
  'taon build:watch:electron',
  'taon docs',
  'taon docs:watch',
  'taon clear',
  'taon release',
  'taon release:auto',
  'taon release:install:locally',
  'taon migration:create',
  'taon migration:run',
  'taon migration:revert',
  'taon vscode:temp:show',
  'taon vscode:temp:hide',
];

export const THIS_IS_GENERATED_STRING = `THIS FILE IS GENERATED - DO NOT MODIFY`;
export const THIS_IS_GENERATED_INFO_COMMENT = `// ${THIS_IS_GENERATED_STRING}`;

export const OVERRIDE_FROM_TNP = [
  'activationEvents',
  'author',
  'bugs',
  'categories',
  'description',
  'engines',
  'homepage',
  'keywords',
  'license',
  'private',
  'repository',
  'scripts',
];

let globalSpinner: ora.Ora;

//#region @backend
globalSpinner = global.spinner;
//#endregion

export { globalSpinner };

export const migration_index_autogenerated_ts =
  'migrations_index._auto-generated_.ts';

export const migrationIndexAutogeneratedTsFileRelativeToSrcPath =
  crossPlatformPath([
    config.folder.migrations,
    migration_index_autogenerated_ts,
  ]);

export const USE_IN_HOST_CONFIG_FULL_CONTEXT_PATH = false;

export const MIGRATION_CONST_PREFIX = 'MIGRATIONS_CLASSES_FOR_';

let taonUsingBundledCliMode = false;

//#region @backend
taonUsingBundledCliMode = !!global.taonUsingBundledCliMode;
//#endregion

export { taonUsingBundledCliMode };

export const UNIT_TEST_TIMEOUT = 30000;
export const INTEGRATION_TEST_TIMEOUT = 30000;

export const USE_MIGRATIONS_DATA_IN_HOST_CONFIG = false;

export const COMPILATION_COMPLETE_LIB_NG_BUILD =
  'Compilation complete. Watching for file changes';

export const COMPILATION_COMPLETE_APP_NG_SERVE = 'Compiled successfully';

// TODO get this from cli, global
export const DEFAULT_FRAMEWORK_VERSION =
  `v${CURRENT_PACKAGE_VERSION.split('.')[0]}` as CoreModels.FrameworkVersion;

let taonRepoPathUserInUserDir: string = '';

//#region @backend
taonRepoPathUserInUserDir = crossPlatformPath([
  UtilsOs.getRealHomeDir(),
  dotTaonFolder,
  taonContainers,
]);
//#endregion

const taonBasePathToGlobalDockerTemplates: string = crossPlatformPath([
  UtilsOs.getRealHomeDir(),
  dotTaonFolder,
  dockerTemplates,
]);

export { taonRepoPathUserInUserDir, taonBasePathToGlobalDockerTemplates };

/**
 * Prevents taon from checking core container when
 * calling itself from child process
 */
export const SKIP_CORE_CHECK_PARAM = '--skipCoreCheck';

export const argsToClear = [
  'websql',
  'serveApp',
  'skipNodeModules',
  'skipSmartContainerDistInit',
  'copyto',
  'port',
  'branding',
  'struct',
  'verbose',
];

export const folder_shared_folder_info = 'shared_folder_info.txt';
export const taonConfigSchemaJsonStandalone =
  'taon-config-standalone.schema.json';
export const taonConfigSchemaJsonContainer =
  'taon-config-container.schema.json';

export const TEMP_DOCS = 'tmp-documentation';

const libsAppPortsFolder = 'libs-apps-ports';

export const HOST_BACKEND_PORT = 'HOST_BACKEND_PORT';
export const tmp_HOST_BACKEND_PORT = `${dotTaonFolder}/${libsAppPortsFolder}/${HOST_BACKEND_PORT}`;

export const FRONTEND_WEBSQL_APP_PORT = 'FRONTEND_WEBSQL_APP_PORT';
export const tmp_FRONTEND_WEBSQL_APP_PORT = `${dotTaonFolder}/${libsAppPortsFolder}/${FRONTEND_WEBSQL_APP_PORT}`;

export const FRONTEND_NORMAL_APP_PORT = 'FRONTEND_NORMAL_APP_PORT';
export const tmp_FRONTEND_NORMAL_APP_PORT = `${dotTaonFolder}/${libsAppPortsFolder}/${FRONTEND_NORMAL_APP_PORT}`;

export const FRONTEND_NORMAL_ELECTRON_PORT = 'FRONTEND_NORMAL_ELECTRON_PORT';
export const tmp_FRONTEND_NORMAL_ELECTRON_PORT = `${dotTaonFolder}/${libsAppPortsFolder}/${FRONTEND_NORMAL_ELECTRON_PORT}`;

export const DEFAULT_PORT = {
  DIST_SERVER_DOCS: 4000,
  APP_BUILD_LOCALHOST: 4200,
  SERVER_LOCALHOST: 4100,
  DEBUGGING_CLI_TOOL: 9222,
  DEBUGGING_ELECTRON: 9888,
};

export const docsConfigJsonFileName = 'docs-config.jsonc';
export const docsConfigSchema = 'docs-config.schema.json';
export const customDefaultCss = 'custom-default.css';
export const customDefaultJs = 'custom-default.js';

export const frameworkBuildFolders = Utils.uniqArray([
  'firedev',
  'taon',
  'tnp',
  `${config.frameworkName}`,
])
  .filter(f => !!f)
  .map(f => `.${f}`);

export const envTs = 'env.ts';

export const environmentsFolder = 'environments';

export const coreRequiredEnvironments = [
  '__',
  'prod',
] as CoreModels.EnvironmentNameTaon[];

//#region methods & getters / get browser ver path
/**
 * @deprecated
 */
export const getBrowserVerPath = (websql: boolean = false) => {
  //#region @backend
  return websql ? config.folder.websql : config.folder.browser;
  //#endregion
};
//#endregion

/**
 * @deprecated not needed probably
 */
export const result_packages_json = 'result-packages.json';

export const readmeMdMainProject = 'README.md';

export const tmpIsomorphicPackagesJson = 'tmp-isomorphic-packages.json';

/**
 * If exist - copy manager will clean copy bundled package to destinations
 */
export const tmpAlreadyStartedCopyManager = 'tmp-already-started-copy-manager';

export const tmpAllAssetsLinked = 'tmp-all-assets-linked';

/**
 * Destination place for all taon processes (tsc, ng build, etc)
 * From this folder code is copied to final destinations node_modules
 */
export const tmpLocalCopytoProjDist = 'tmp-local-copyto-proj-dist';

/**
 * Folder where tmpSrdDist code is cutted file by file before publishing
 */
export const tmpCutReleaseSrcDist = 'tmp-cut-release-src-dist';

/**
 * Folder where tmpSrdDist code is cutted file by file before publishing (websql version)
 */
export const tmpCutReleaseSrcDistWebsql = 'tmp-cut-release-src-dist-websql';

/**
 * Temporary folder for base href overwrite during build
 * (taon library build sets it)
 */
export const tmpBaseHrefOverwrite = 'tmp-base-href-overwrite';

/**
 * Temporary folder for vscode project files
 */
export const tmpVscodeProj = `tmp-vscode-proj`;

/**
 * Taon code transformed for backend
 */
export const tmpSourceDist = 'tmp-source-dist';
/**
 * Taon code transformed for backend in websql mode
 * (this code is probably never used)
 */
export const tmpSourceDistWebsql = 'tmp-source-dist-websql';

/**
 * Taon code transformed for browser
 */
export const tmpSrcDist = 'tmp-src-dist';
/**
 * Taon code transformed for browser in websql mode
 */
export const tmpSrcDistWebsql = 'tmp-src-dist-websql';

/**
 * Taon code transformed for browser (angular app uses this)
 */

export const tmpSrcAppDist = 'tmp-src-app-dist';

/**
 * Taon code transformed for browser (angular app in websql uses this)
 */
export const tmpSrcAppDistWebsql = 'tmp-src-app-dist-websql';

export const defaultConfiguration = 'defaultConfiguration';

/**
 * template folders from isomorphic lib
 */
export enum TemplateFolder {
  /**
   * Core project for angular app webapp, library and electron app
   */
  templateApp = 'template-app',

  /**
   * @deprecated
   * Core project angular library
   */
  // templateLib = 'template-lib',

  /**
   * @deprecated
   * Core project template for electron app
   */
  // templateElectron = 'template-electron',
}

export enum AngularJsonTaskName {
  ANGULAR_APP = 'app',
  ELECTRON_APP = 'angular-electron',
}

export enum CoreAssets {
  sqlWasmFile = 'sql-wasm.wasm',
  mainFont = 'flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2',
}

export const dockerTemplatesFolder = 'docker-templates';

export enum DockerTemplatesFolders {
  ANGULAR_APP_NODE = 'angular-app-node',
  ANGULAR_APP_SSR_NODE = 'angular-app-ssr-node',
  BACKEND_APP_NODE = 'backend-app-node',
  DATABASE_MYSQL = 'database-mysql',
}

export enum CoreNgTemplateFiles {
  sqlJSLoaderTs = 'sqljs-loader.ts',
  SERVER_TS = 'server.ts',
  JEST_CONFIG_JS = 'jest.config.js',
  SETUP_JEST_TS = 'setupJest.ts',
  JEST_GLOBAL_MOCKS_TS = 'jestGlobalMocks.ts',
  NG_PACKAGE_JSON = 'ng-package.json',
  PACKAGE_JSON = 'package.json', // fileName.package_json,
  ANGULAR_JSON = 'angular.json', // fileName.angular_json,
  INDEX_HTML_NG_APP = 'index.html',
  FAVICON_ICO = 'favicon.ico',
  WEBMANIFEST_JSON = 'manifest.webmanifest',
}

export enum TaonGeneratedFiles {
  BUILD_INFO_MD = 'BUILD-INFO.md',
  build_info_generated_ts = 'build-info._auto-generated_.ts',
  index_generated_ts = 'index._auto-generated_.ts',
  BUILD_INFO_AUTO_GENERATED_JS = 'build-info._auto-generated_.js',
  MIGRATIONS_INFO_MD = 'migrations-info.md',
  MOCHA_TESTS_INFO_MD = 'mocha-tests-info.md',
  SHARED_FOLDER_INFO_TXT = 'shared_folder_info.txt',
  APP_HOSTS_TS = 'app.hosts.ts',
  LAUNCH_JSON = 'launch.json',
  LAUNCH_BACKUP_JSON = 'launch-backup.json',
  VARS_SCSS = 'vars.scss',
  LIB_INFO_MD = 'lib-info.md',
  APP_FOLDER_INFO_MD = 'app-folder-info.md',
}

export enum TaonGeneratedFolders {
  ENV_FOLDER = 'env',
  COMPILED = 'compiled',
}

/**
 * Main project /dist folder
 */
export const nodeModulesMainProject = folderName.node_modules;

/**
 * Main project /dist folder
 */
export const distMainProject = folderName.dist;

/**
 * Main project /dist-nocutsrc folder (d.ts files without code cutting)
 */
export const distNoCutSrcMainProject = `dist-nocutsrc`;

/**
 * Vscode project dist folder
 */
export const distVscodeProj = folderName.dist;

/**
 * Electron project dist folder
 */
export const distElectronProj = folderName.dist;

export const electronNgProj = 'electron';

export const combinedDocsAllMdFilesFolder = `allmdfiles`;

/**
 * Normal angular app build
 */
export const distFromNgBuild = folderName.dist;

/**
 * Dist from sass loader
 */
export const distFromSassLoader = folderName.dist;

/**
 * Vscode project dist folder
 */
export const outVscodeProj = folderName.out;

/**
 * Main project /docs folder
 */
export const docsMainProject = folderName.docs;

/**
 * Main project /bin folder
 */
export const binMainProject = folderName.bin;

/**
 * Main project /src folder
 */
export const srcMainProject = folderName.src;

/**
 * src from template proxy project
 */
export const srcNgProxyProject = folderName.src;

/**
 * each taon import ends with /src
 */
export const srcFromTaonImport = folderName.src;

/**
 * each taon import ends with /src
 */
export const srcDtsFromNpmPackage = 'src.d.ts';

export const myLibFromNgProject = 'my-lib';

export const libFromNgProject = 'lib';

export const externalLibsFromNgProject = 'external-libs';

/**
 * projects/my-lib form angular lib template
 */
export const projectsFromNgTemplate = folderName.projects;

/**
 * @deprecated special place in standalone project for projects
 */
export const projectsFromMainProject = folderName.projects;

/**
 * Main project app folder from /src/app folder
 */
export const migrationsFromSrc = folderName.migrations;

/**
 * Main project app folder from /tmp-*src folders
 */
export const migrationsFromTempSrc = folderName.migrations;

/**
 * Main project app folder from /src/app folder
 */
export const appFromSrc = folderName.app;

/**
 * Generated app inside angular app (comes from /src/app folder)
 */
export const appFromSrcInsideNgApp = folderName.app;

/**
 * Main project lib folder from /src/lib folder
 */
export const libFromSrc = folderName.lib;

/**
 * Lib from taon import
 */
export const libFromImport = folderName.lib;

/**
 * Lib from dist/lib
 */
export const libFromCompiledDist = folderName.lib;

/**
 * Lib from npm packages
 */
export const libFromNpmPackages = folderName.lib;

/**
 * Main project tests folder from /src/tests folder
 */
export const testsFromSrc = folderName.tests;

/**
 * Main project assets from /src/assets folder
 */
export const assetsFromSrc = folderName.assets;

/**
 * Assets stored in taon isomorphic npm package with
 */
export const assetsFromNpmLib = folderName.assets;

/**
 * Main project assets from /tmp-*\/src/assets folder
 */
export const assetsFromTempSrc = folderName.assets;

/**
 * Assets from ng template project
 */
export const assetsFromNgProj = folderName.assets;

/**
 * Assets from npm package
 */
export const assetsFromNpmPackage = folderName.assets;

/**
 * Shared from assets from /src/assets/shared folder
 */
export const sharedFromAssets = folderName.shared;

/**
 * Generated folder in assets from /src/assets/generated folder
 */
export const generatedFromAssets = folderName.generated;

/**
 * Generated pwa assets from /src/assets/generated/pwa folder
 */
export const pwaGeneratedFolder = 'pwa';

/**
 * Generated assets-for folder
 */
export const assetsFor = 'assets-for';

/**
 * @deprecated it was probably needed for old container build
 * Folder for all browser libs
 */
export const libs = folderName.libs;

export enum BundledFiles {
  CNAME = 'CNAME',
  README_MD = 'README.md',
  CLI_README_MD = 'CLI-README.md',
  INDEX_HTML = 'index.html',
}

export enum AngularJsonAppOrElectronTaskName {
  developmentSsr = 'development',
  productionSsr = 'production',
  developmentStatic = 'development-static',
  productionStatic = 'production-static',
}

export const AngularJsonAppOrElectronTaskNameResolveFor = (
  envOptions: EnvOptions,
): AngularJsonAppOrElectronTaskName => {
  if (envOptions.build.websql || !envOptions.build.ssr) {
    if (!envOptions.build.watch && !!envOptions.release.releaseType) {
      return AngularJsonAppOrElectronTaskName.productionStatic;
    } else {
      return AngularJsonAppOrElectronTaskName.developmentStatic;
    }
  } else {
    if (!envOptions.build.watch && !!envOptions.release.releaseType) {
      return AngularJsonAppOrElectronTaskName.productionSsr;
    } else {
      return AngularJsonAppOrElectronTaskName.developmentSsr;
    }
  }
};

export enum AngularJsonLibTaskName {
  development = 'development',
  production = 'production',
}

export const AngularJsonLibTaskNameResolveFor = (
  envOptions: EnvOptions,
): AngularJsonLibTaskName => {
  if (!envOptions.build.watch && !!envOptions.release.releaseType) {
    return AngularJsonLibTaskName.production;
  } else {
    return AngularJsonLibTaskName.development;
  }
};

export enum BundledDocsFolders {
  VERSION = 'version',
}

export enum TaonCommands {
  NPM_RUN_NG = 'npm-run ng',
  NG = 'ng',
}

export const appTsFromSrc = 'app.ts';

export const appScssFromSrc = 'app.scss';

export const globalScssFromSrc = 'global.scss';

export const ngProjectStylesScss = 'styles.scss';

export const appElectronTsFromSrc = 'app.electron.ts';

export const appVscodeTsFromSrc = 'app.vscode.ts';

export const appVscodeJSFromBuild = 'app.vscode.js';

export enum TaonFileExtension {
  DOT_WORKER_TS = '.worker.ts',
  DOT_CONTEXT_TS = '.context.ts',
}

/**
 * ng build for library from /src/lib
 */
export const tmpLibsForDist = 'tmp-libs-for-dist';
/**
 * ng build for library from /src/lib (websql code)
 */
export const tmpLibsForDistWebsql = 'tmp-libs-for-dist-websql';

/**
 * normal angular app build
 */
export const tmpAppsForDist = 'tmp-apps-for-dist';
/**
 * websql angular app build
 */
export const tmpAppsForDistWebsql = 'tmp-apps-for-dist-websql';
/**
 * electron angular app build
 */
export const tmpAppsForDistElectron = `tmp-apps-for-dist-electron`;

export const tmpAppsForDistElectronWebsql = `tmp-apps-for-dist-websql-electron`;

/**
 * Dummy auto generated /src/index.ts
 */
export const indexTsFromSrc = fileName.index_ts;

/**
 * Entry point for angular lib from /src/lib/index.ts
 */
export const indexTsFromLibFromSrc = fileName.index_ts;

/**
 * Entry point for scss from /src/index.scss
 */
export const indexScssFromSrc = fileName.index_ts;

/**
 * Index for autogenerated migrations /src/migrations/index.ts
 */
export const indexTsFromMigrationsFromSrc = fileName.index_ts;

/**
 * Entry point for scss from /src/lib/index.scss
 */
export const indexScssFromSrcLib = 'index.scss';

/**
 *
 * @param appForLib if true code is for angular (ng server/build) app build, false for lib ng build
 * @param websql if true websql version
 * @returns relative path to temp browser source folder
 */
export function tempSourceFolder(appForLib: boolean, websql: boolean): string {
  if (appForLib && websql) {
    return tmpSrcAppDistWebsql;
  }
  if (appForLib && !websql) {
    return tmpSrcAppDist;
  }
  if (!appForLib && websql) {
    return tmpSrcDistWebsql;
  }
  if (!appForLib && !websql) {
    return tmpSrcDist;
  }
}

export const ENV_INJECT_COMMENT = '<!--ENV_INJECT-->';
export const isomorphicPackagesJsonKey = 'isomorphicPackages';

export const browserMainProject = config.folder.browser;
export const browserNgBuild = config.folder.browser;
export const websqlMainProject = config.folder.websql;

export const clientCodeVersionFolder = [browserMainProject, websqlMainProject];

export const notAllowedAsPacakge = [...clientCodeVersionFolder, assetsFromSrc];

export const MESSAGES = {
  SHUT_DOWN_FOLDERS_AND_DEBUGGERS:
    'Please shut down your code debugger and any open windows from node_modules and press any key...',
};

export const localReleaseMainProject = 'local_release';

export const dotInstallDate = '.install-date';

export const dotVscodeMainProject = '.vscode';

export const packageJsonLockMainProject = fileName.package_lock_json;

export const yarnLockMainProject = fileName.yarn_lock;

export const packageJsonMainProject = fileName.package_json;

export const packageJsonNpmLib = fileName.package_json;

export const packageJsonVscodePlugin = fileName.package_json;

export const packageJsonNpmLibAngular = fileName.package_json;

export const packageJsonNgProject = fileName.package_json;

export const tsconfigJsonMainProject = 'tsconfig.json';
export const tsconfigNgProject = 'tsconfig.json';

export const tsconfigSpecNgProject = 'tsconfig.spec.json';

export const tsconfigForUnitTestsNgProject = 'tsconfig.spec-for-unit.json';

export const tsconfigJsonBrowserMainProject = 'tsconfig.browser.json';

export const tsconfigBackendDistJson = 'tsconfig.backend.dist.json';

export const tsconfigJsonIsomorphicMainProject = 'tsconfig.isomorphic.json';

export const tsconfigIsomorphicFlatDistMainProject =
  'tsconfig.isomorphic-flat-dist.json';

export const dotNpmrcMainProject = fileName._npmrc;

export const dotGitIgnoreMainProject = fileName._gitignore;

export const dotNpmIgnoreMainProject = fileName._npmignore;

export const webpackConfigJsMainProject = 'webpack.config.js';

export const esLintConfigJsonMainProject = 'eslint.config.js';

export const runJsMainProject = 'run.js';

export const indexDtsMainProject = fileName.index_d_ts;

export const indexDtsNpmPackage = fileName.index_d_ts;

export const indexJSNpmPackage = fileName.index_js;

export const indexJSElectronDist = fileName.index_js;

export const cliTsFromSrc = 'cli.ts';

export const cliJSNpmPackage = 'cli.js';

export const cliJSMapNpmPackage = 'cli.js.map';

export const cliDtsNpmPackage = 'cli.d.js';

export const indexJsMainProject = fileName.index_js;

export const indexJsMapMainProject = fileName.index_js_map;

export const sourceLinkInNodeModules = folderName.source;

export const taonJsonMainProject = fileName.taon_jsonc;

export const updateVscodePackageJsonJsMainProject =
  'update-vscode-package-json.js';

export const routes = TaonTempRoutesFolder;

export const databases = TaonTempDatabasesFolder;

export const dotFileTemplateExt = '.filetemplate';

export const dotEnvFile = '.env';

export const suffixLatest = '-latest';

export const releaseSuffix = '-release';

export const debugSuffix = '--debug';

export const debugBrkSuffix = '--debug-brk';

export const inspectSuffix = '--inspect';

export const inspectBrkSuffix = '--inspect-brk';

export const containerPrefix = 'container-';

export const testEnvironmentsMainProject = folderName.testsEnvironments;

export const ONLY_COPY_ALLOWED = [
  // 'background-worker-process',
  'better-sqlite3',
  '.bin',
  '.install-date',
];

/**
 * to prevent lib error when building with asserts
 */
export const TO_REMOVE_TAG = `/${'TO_REMOVE'
  .split('')
  .map(c => _.times(8, () => c).join(''))
  .join('')}`;

export const ERR_MESSAGE_DEPLOYMENT_NOT_FOUND = 'DEPLOYMENT_NOT_FOUND';
export const ERR_MESSAGE_PROCESS_NOT_FOUND = 'PROCESS_NOT_FOUND';
// console.log('TO_REMOVE_TAG', TO_REMOVE_TAG);
