/**
 *  Autogenerated by current cli tool
 */
export declare const BUILD_FRAMEWORK_CLI_NAME = "tnp";
/**
 *  This value can be change in taon.jsonc (appId)
 */
export declare const APP_ID = "dev.taon.cli.tnp";
/**
 *  Autogenerated by current cli tool
 */
export declare const BUILD_BASE_HREF = "";
/**
 *  This value can be change in taon.jsonc (overrideNpmName)
 */
export declare const PROJECT_NPM_NAME = "tnp";
/**
 * Taon version from you project taon.json
 */
export declare const CURRENT_PACKAGE_TAON_VERSION = "v21";
/**
 *  Autogenerated by current cli tool. Use *tnp release* to bump version.
 */
export declare const CURRENT_PACKAGE_VERSION = "21.0.155";
