import { crossPlatformPath } from 'tnp-core/src';
import { _ } from 'tnp-core/src';
import { Helpers } from 'tnp-helpers/src';
import { BaseFeatureForProject } from 'tnp-helpers/src';

import type { Project } from '../../../project';

export interface AppBuildConfig {
  build?: boolean;
  prod?: boolean;
  websql?: boolean;
  projName?: string;
  children?: AppBuildConfig[];
}

// @ts-ignore TODO weird inheritance problem
export class GithubPagesAppBuildConfig extends BaseFeatureForProject<Project> {
  private oldConfigName = 'docs-app-build-config.json5';
  private get configFileName() {
    //#region @backendFunc
    return 'github-pages-app-build-config.jsonc';
    //#endregion
  }

  private get path() {
    //#region @backendFunc
    this.replaceOldConfig();
    return crossPlatformPath([this.project.location, this.configFileName]);
    //#endregion
  }

  get configExists() {
    //#region @backendFunc
    return Helpers.exists(this.path);
    //#endregion
  }

  private replaceOldConfig() {
    //#region @backendFunc
    if (this.project.hasFile(this.oldConfigName)) {
      this.project.writeFile(
        this.configFileName,
        this.project.readFile(this.oldConfigName),
      );
      this.project.removeFile(this.oldConfigName);
    }
    //#endregion
  }

  get config() {
    //#region @backendFunc
    let cfg = Helpers.readJson(this.path, void 0, true) as AppBuildConfig;
    cfg = this.fix(cfg);
    return cfg;
    //#endregion
  }

  private fix(cfg: AppBuildConfig): AppBuildConfig {
    //#region @backendFunc
    if (!cfg) {
      cfg = { build: this.project.framework.isStandaloneProject };
    }
    if (this.project.framework.isStandaloneProject) {
      cfg.projName = this.project.name;
    }
    if (this.project.framework.isSmartContainer) {
      cfg.projName = this.project.framework.smartContainerBuildTarget.name;
    }

    cfg.build = !!cfg.build;
    cfg.prod = !!cfg.prod;
    cfg.websql = !!cfg.websql;
    cfg.children = cfg.children || [];
    if (this.project.framework.isSmartContainer) {
      const children = this.project.children.map(c => c.name);
      cfg.children = cfg.children.filter(c => children.includes(c.projName));
    }

    for (let index = 0; index < cfg.children.length; index++) {
      cfg.children[index] = this.fix(cfg.children[index]);
    }
    return cfg;
    //#endregion
  }

  save(cfg: AppBuildConfig) {
    //#region @backendFunc
    Helpers.writeFile(
      this.path,
      `// This file is generated by command: taon release
// With this configuration you can use: taon automatic:release:docs
${JSON.stringify(cfg, null, 2)}

    `,
    );
    //#endregion
  }
}
