//#region imports
import { ChangeOfFile } from 'incremental-compiler/src';
import { config } from 'tnp-core/src';
import {
  Helpers,
  _,
  UtilsMigrations,
  crossPlatformPath,
  path,
} from 'tnp-core/src';
import {
  BaseFeatureForProject,
  BaseDebounceCompilerForProject,
  UtilsTypescript,
} from 'tnp-helpers/src';

import {
  indexTsFromMigrationsFromSrc,
  MIGRATION_CONST_PREFIX,
  migration_index_autogenerated_ts,
  migrationIndexAutogeneratedTsFileRelativeToSrcPath,
  migrationsFromSrc,
  srcMainProject,
  THIS_IS_GENERATED_INFO_COMMENT,
} from '../../../../../constants';
import type { Project } from '../../../project';
//#endregion

export class MigrationHelper extends BaseDebounceCompilerForProject<
  {}, // @ts-ignore TODO weird inheritance problem
  Project
> {

  //#region constructor
  constructor(project: Project) {
    super(project, {
      folderPath: project.pathFor([srcMainProject, migrationsFromSrc]),
      taskName: 'MigrationHelper',
      notifyOnFileUnlink: true,
    });
  }
  //#endregion

  //#region migration index autogenerated ts file

  get migrationIndexAutogeneratedTsFileAbsPath(): string {
    return this.project.pathFor([
      srcMainProject,
      migrationIndexAutogeneratedTsFileRelativeToSrcPath,
    ]);
  }
  //#endregion

  //#region rebuild
  rebuild(
    relativePathsWithClasses: {
      relativePath: string;
      absPath: string;
      classes: string[];
    }[],
  ) {

    //#region @backendFunc
    Helpers.taskStarted(`Rebuilding migration index file...`);
    const allClassesByTimestamp: string[] = relativePathsWithClasses
      .reduce((acc, c) => acc.concat(c.classes), [])
      .sort((classA, classB) => {
        const timestampA = UtilsMigrations.getTimestampFromClassName(classA);
        const timestampB = UtilsMigrations.getTimestampFromClassName(classB);

        return timestampA - timestampB; // Ascending order
      });

    const allContexts = allClassesByTimestamp.reduce(
      (alreadyAddedClassesObj, className) => {
        const contextName: string = _.first(className.split('_')) || '';
        if (!alreadyAddedClassesObj[contextName]) {
          alreadyAddedClassesObj[contextName] = [];
        }
        alreadyAddedClassesObj[contextName].push(className);
        return alreadyAddedClassesObj;
      },
      {},
    );
    const allImports = relativePathsWithClasses
      .filter(c => c.classes.length >= 1)
      .map(c => {
        return (
          `import { ${c.classes.join(', ')} } from ` +
          `'./${c.relativePath.replace('.ts', '')}';`
        );
      });
    // console.log('MigrationHelper rebuild for ', relativePathsWithClasses);

    // export const MIGRATIONS_CLASSES = [${allClasses.join(',\n')}];
    Helpers.writeFile(
      this.migrationIndexAutogeneratedTsFileAbsPath,
      `
${THIS_IS_GENERATED_INFO_COMMENT}
${allImports.join('\n')}
${THIS_IS_GENERATED_INFO_COMMENT}
${_.keys(allContexts)
  .map(contextName => {
    const classes = allContexts[contextName];
    return (
      `export const ${MIGRATION_CONST_PREFIX}${contextName}` +
      ` = {${classes
        .map(c => {
          return `/* ${UtilsMigrations.getFormattedTimestampFromClassName(c)} */ ${c}`;
        })
        .join(',\n ')}};`
    );
  })
  .join('\n')}
${THIS_IS_GENERATED_INFO_COMMENT}
      `,
    );
    UtilsTypescript.formatFile(this.migrationIndexAutogeneratedTsFileAbsPath);
    Helpers.taskDone(`Rebuilding migration index Done`);
    //#endregion

  }
  //#endregion

  //#region action
  action({
    changeOfFiles,
    asyncEvent,
  }: {
    changeOfFiles: ChangeOfFile[];
    asyncEvent: boolean;
  }) {

    //#region @backendFunc
    changeOfFiles = changeOfFiles.filter(c => {
      return (
        c.fileAbsolutePath.endsWith('.ts') &&
        path.basename(c.fileAbsolutePath) !== migration_index_autogenerated_ts
      );
    });
    if (changeOfFiles.length === 0) {
      // console.log('MigrationHelper action skipped');
      return;
    }

    if (
      !this.project.hasFile([
        srcMainProject,
        migrationsFromSrc,
        indexTsFromMigrationsFromSrc,
      ])
    ) {
      Helpers.writeFile(
        this.project.pathFor([
          srcMainProject,
          migrationsFromSrc,
          indexTsFromMigrationsFromSrc,
        ]),
        `//@ts-nocheck
export * from './${migration_index_autogenerated_ts.replace('.ts', '')}';
        `.trim() + '\n',
      );
    }

    // console.log('MigrationHelper action for ', changeOfFiles);
    this.rebuild(
      this.exitedFilesAbsPathes
        .filter(f => f.endsWith('.ts') && !f.endsWith('._auto-generated_.ts'))
        .map(c => {
          return {
            absPath: c,
            relativePath: this.project
              .relative(c)
              .split('/')
              .slice(2)
              .join('/'),
            classes: UtilsTypescript.extractClassNamesFromFile(c),
          };
        }),
    );
    //#endregion

  }
  //#endregion

}