import { ChangeOfFile } from 'incremental-compiler';
import { BaseDebounceCompilerForProject } from 'tnp-helpers';
import type { Project } from '../../../project';
export declare class MigrationHelper extends BaseDebounceCompilerForProject<{}, // @ts-ignore TODO weird inheritance problem
Project> {
    constructor(project: Project);
    get migrationIndexAutogeneratedTsFileAbsPath(): string;
    rebuild(relativePathsWithClasses: {
        relativePath: string;
        absPath: string;
        classes: string[];
    }[]): void;
    action({ changeOfFiles, asyncEvent, }: {
        changeOfFiles: ChangeOfFile[];
        asyncEvent: boolean;
    }): void;
}